
export const artisans = [
'Maria Concepción Alfonso',
'Ovidio Quirós',
'Cristian Durango',
'Alicia Zapata',
'Claudia Saldarriaga',
'Edilia Hurtado',
'Ofelia Ruiz	',
'Oneida Ariza',
'Marta Ligia Jaramillo ',
'Cristina Montoya ',
'Paola Salcedo	',
'María Victoria Correa ',
'Olga Rocío Vargas',
'Olga Lucía Calderón',
'Geraldine García',
'Gilma Londoño	',
'Marta Elena Pérez',
'Olga Cecilia Hincapié ',
'Miriam Elena Llanes	',
'Liliana Ortiz',
'Liliana Maria Usuga',
]